### ISSUE TITLE
Instead of invoking pause>nul use the getpass function to suspend script execution.

### ISSUE THREAD

**Issue by Aetopia** [couleur-tweak-tips/Smoothie#10]
```py
if exitcode != 0:
        print(f"Something went wrong with {video}, press any key to un-pause")
        if isWin: system('pause>nul')
        exit()
```
Instead using `pause>nul`, You can use `getpass` module and its function `getpass` to suspend script execution.

Unlike `input()`, `getpass()` doesn't show the contents of the user's input, making it an effective alternative to `pause>nul`.

https://user-images.githubusercontent.com/41850963/165290274-49b1a7d4-063c-49df-b21a-0b4d673e0f50.mp4

.

**Comment by couleurm** [comment]
the problem with getpass is that you can only press enter to continue

i think i'll make Smoothie use `cmd /k` in the next update,

if it exists it'll simply drop to cmd
else it runs exit

thanks
