### ISSUE TITLE
Packaging Smoothie

### ISSUE THREAD

**Issue by he3als** [couleur-tweak-tips/Smoothie#11]
I think it would be useful and good if there was an AUR package for Smoothie for Arch Linux users to easily access, update and install Smoothie. I might look into making an AUR package for Smoothie too.

**Comment by UltraToon** [comment]
I may start working on it, but currently the install script will be a attempt to work on ubuntu/debian and arch based distributions.
Yeah, making a AUR package of Smoothie and putting required dependencies makes the install script much shorter and more reliable, if only one of us will update the PKGBUILD every now and then when a update occurs.

**Comment by couleurm** [comment]
unless someone takes a lot of time to make a huge bash script with all checks i'd only accept an AUR package

**Comment by relimS** [comment]
> unless someone takes a lot of time to make a huge bash script with all checks i'd only accept an AUR package

*cough*

Anyways, I'll try working on a PKGBUILD. Shouldn't be hard, right?

**Comment by relimS** [comment]
We will need an AUR package for vs-frameblender and we will need to change the pkgver for every commit. I don't think I can do that

**Comment by couleurm** [comment]
ultratoon said he'll make one

**Comment by couleurm** [comment]
wouldn't it be possible to make the installation script curl vs-frameblender if it doesn't exist?

**Comment by he3als** [comment]
can't u just get it from the aur?

**Comment by sh9r** [comment]
The aur also has to be responsible for moving all the plugins into their proper spots

**Comment by Aetopia** [comment]
If possible, could the aur package recompile the vs-frameblender .so?

**Comment by couleurm** [comment]
i think we should have a separate `PKGBUILD` for `smoothie-git` and `vapoursynth-plugin-frameblender`

**Comment by couleurm** [comment]
This is inactive, making a separate AUR issue
