### ISSUE TITLE
Define windows in the name for ps1

### ISSUE THREAD

**Issue by UltraToon** [couleur-tweak-tips/Smoothie#12]
Hey, make sure to put something like 'windowsinstall.ps1' instead of install.ps1 or something, just please do this little change

Ive seen people on linux install powershell and setup everything to use a ps1 instead of sh on linux, useless pain.

**Comment by couleurm** [comment]
https://github.com/couleur-tweak-tips/Smoothie/commit/4575da8ff646d9af0d8fc16b847ada040a1e7e20
