### ISSUE TITLE
List Python Packages required for Smoothie.

### ISSUE THREAD

**Issue by Aetopia** [couleur-tweak-tips/Smoothie#13]

**Comment by couleurm** [comment]
## pip packages
* [DearPyGui ](https://github.com/hoffstadt/DearPyGui) - to make a graphical user interface
* [yaspin](https://github.com/pavdmyt/yaspin) - for the nice spinner to wait while it indexes your clips
* [tkinter](https://docs.python.org/3/library/tkinter.html) for the file open dialog
* [pywin32](https://github.com/davidmarble/pywin/) for changing window position / stay on top behavior
* [pyyaml](https://pypi.org/project/PyYAML/) to parse and dump the YAML config
* [PyTaskbar](https://github.com/somePythonProgrammer/PyTaskbar) - progress bar in taskbar

## VapourSynth
* scripts:
	  * `adjust` - for basic color correction, haven't implemented it yet
	  * `filldrops` 
	  * [havsfunc](https://github.com/HomeOfVapourSynthEvolution/havsfunc) for it's `ChangeFPS` function and InterFrame2 script
	  * [msvfunc](https://github.com/HomeOfVapourSynthEvolution/mvsfunc) needed by `havsfunc`
	  * weighting recently rewrote by atzur
* plugins
	  * [mvtools2](https://github.com/dubhater/vapoursynth-mvtools): interpolation and rsmb stuff
	  * [svpflow1 & 2](https://github.com/bjaan/smoothvideo/blob/main/SVPflow_LastGoodVersions.7z): interpolation stuff
	  * [vs-frameblender](https://github.com/couleurm/vs-frameblender): does the frame blending, wow
	  * [ffms2](https://github.com/FFMS/ffms2): to  take clip as input

Will update this later if dependencies grow/change

**Comment by Aetopia** [comment]
Add it as part of the README.

**Comment by couleurm** [comment]
done https://github.com/couleur-tweak-tips/Smoothie/wiki/Bundling-Smoothie-yourself
