### ISSUE TITLE
Video outputs as MKV even if I change the container to .mp4

### ISSUE THREAD

**Issue by citrusyummer** [couleur-tweak-tips/Smoothie#18]
The video will always output as MKV that cannot be read by most of my programs, and every single video I have to convert to mp4

**Comment by SnowzNZ** [comment]
Please provide your config and what is the input container?

**Comment by X3sion** [comment]
Hi I have the same problem.

Sorry if I ask anything stupid, cause I have no idea what's going on here. But if by input container you mean the extension of the video I'm putting into smoothie, **it's mp4**.

And if by config you mean my settings in recipe, **it's this**:

interpolation:
  enabled: yes
  fps: 400
  mask: weak
  speed: medium
  tuning: film
  algorithm: 13
  gpu: true

frame blending:
  enabled: yes
  fps: 60
  intensity: 1.75
  weighting: equal

flowblur:
  enabled: yes
  amount: 100
  mask:apex

encoding:
  process: ffmpeg.exe
  args: hevc_nvenc -rc constqp -preset p7 -qp 18

misc:
  mpv bin: mpv
  stay on top: true
  verbose: false
  ding after: 1
  folder: 
  container: mp4
  flavors: fruits
  dedupthreshold: 0.1

timescale:
  in: 1.0
  out: 1.0

I also have a problem, where I'm using remux.bat to convert said exported video by smoothie, and it's not converting the file properly. It always gives me this error:

codec frame size is not set remux mkv

**Comment by couleurm** [comment]
Type in `rc` in Run (Windows+R) to open the YAML config file, I've accidentally left the old .INI one that does not do anything
