### ISSUE TITLE
Smoothie for the AUR

### ISSUE THREAD

**Issue by couleurm** [couleur-tweak-tips/Smoothie#21]
feel free to discuss / suggest about these two planned AUR packages:

`smoothie-git`

`vapoursynth-plugin-frameblender`

**Comment by animafps** [comment]
added `vapoursynth-plugin-frameblender` to the AUR with the release version (1.2) https://aur.archlinux.org/packages/vapoursynth-plugin-frameblender

**Comment by couleurm** [comment]
thanks for packaging it!

**Comment by couleurm** [comment]
If I switch back to arch I'll consider this
